# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Word Count' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Word Count
  pod 'SwiftyStoreKit'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Crash'
  pod 'Firebase/AdMob'

end
