# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bubble Ninja' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyStoreKit'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Crash'
  pod 'Firebase/AdMob'

  # Pods for Bubble Ninja


end
